In [1]:
import numpy as np

array = np.array([
    [3, 7, 1],
    [10, 3, 2],
    [5, 6, 7]
])
print(array)
print()

# Sorting along each row
print(np.sort(array, axis=1))
print()

# Sorting along each column
print(np.sort(array, axis=0))

[[ 3  7  1]
 [10  3  2]
 [ 5  6  7]]

[[ 1  3  7]
 [ 2  3 10]
 [ 5  6  7]]

[[ 3  3  1]
 [ 5  6  2]
 [10  7  7]]
